\set ON_ERROR_STOP on
begin;
select set_config('app.product10d_test_enforce','on',true);
create temporary table results(n serial,label text,passed boolean) on commit drop;
create temporary table fixture_ids(user_id uuid,tenant_id uuid) on commit drop;
create function pg_temp.assert_true(label text,value boolean) returns void language plpgsql as $$begin
 if value is distinct from true then raise exception 'FAIL: %',label; end if; insert into results(label,passed) values(label,true);
end;$$;
create function pg_temp.rpc(actor uuid,statement text) returns jsonb language plpgsql as $$
declare result jsonb;
begin
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role',case when actor is null then 'anon' else 'authenticated' end)::text,true);
 perform set_config('request.jwt.claim.sub',coalesce(actor::text,''),true);
 if actor is null then set local role anon; else set local role authenticated; end if;
 execute statement into result;
 reset role;
 perform set_config('request.jwt.claims','{}',true); perform set_config('request.jwt.claim.sub','',true);
 return jsonb_build_object('value',result,'state','00000');
exception when others then
 reset role;
 perform set_config('request.jwt.claims','{}',true); perform set_config('request.jwt.claim.sub','',true);
 return jsonb_build_object('state',sqlstate,'test_error',sqlerrm);
end;$$;

-- Separate owner fixture preserves ownership while the original actor changes role/status.
create function pg_temp.pam_keeper(t uuid) returns void language plpgsql as $keeper$
declare u uuid:=md5(t::text||':pam1b-test-keeper')::uuid;
begin
 insert into auth.users(id,email,email_confirmed_at) values(u,u||'@example.invalid',now()) on conflict(id) do nothing;
 insert into public.tenant_memberships(tenant_id,user_id,role,status) values(t,u,'admin','active') on conflict(tenant_id,user_id) do nothing;
end;$keeper$;
do $test$
declare pa uuid:=gen_random_uuid(); other_user uuid:=gen_random_uuid(); t uuid; p jsonb; r jsonb; q text; request_id uuid:=gen_random_uuid(); e uuid:=gen_random_uuid(); reg uuid:=gen_random_uuid(); lane uuid:=gen_random_uuid(); price_id uuid:=gen_random_uuid(); reservation_id uuid:=gen_random_uuid(); d uuid; challenge jsonb; before_flags jsonb;
begin
 insert into auth.users(id,email)values(pa,pa||'@example.invalid'),(other_user,other_user||'@example.invalid');
 insert into public.platform_admins(user_id,status)values(pa,'active');
 t:=(pg_temp.rpc(pa,format('select to_jsonb(public.platform_create_tenant_v1(%L,%L,%L,%L))','PAM local','pam-local','pam-local-public','Local'))->>'value')::uuid;
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'));
 perform pg_temp.assert_true('preview allowed',p->>'state'='00000');
 perform pg_temp.assert_true('initial revision',p->'value'->>'revision'='0');
 perform pg_temp.assert_true('upgrade allowed',(p->'value'->>'can_apply')::boolean);
 perform pg_temp.assert_true('DTO exact keys',(select array_agg(k order by k) from jsonb_object_keys(p->'value') k)=array['blockers','can_apply','current_plan','features_added','features_removed','revision','target_plan','tenant','warnings']);
 q:=format('select public.platform_change_tenant_plan_v2(%L,%L,%L,%L)',t,'booking_only_v1','0',request_id);
 r:=pg_temp.rpc(pa,q);
 perform pg_temp.assert_true('writer allowed',r->>'state'='00000');
 perform pg_temp.assert_true('revision increment',r->'value'->>'revision'='1');
 perform pg_temp.assert_true('retry same result',pg_temp.rpc(pa,q)=r);
 perform pg_temp.assert_true('audit once',(select count(*)=1 from public.platform_audit_logs where tenant_id=t and action='plan_assigned'));
 perform pg_temp.assert_true('payload conflict',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,%L,%L,%L)',t,'current_full_v1','1',request_id))->>'state'='22023');
 perform pg_temp.assert_true('stale revision',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,%L,%L,%L)',t,'current_full_v1','0',gen_random_uuid()))->>'state'='PT409');
 perform pg_temp.assert_true('ordinary user denied',pg_temp.rpc(other_user,q)->>'state'='42501');
 perform pg_temp.assert_true('anon denied',pg_temp.rpc(null,q)->>'state'='42501');
 perform pg_temp.assert_true('current UI v1 same-plan compatible',pg_temp.rpc(pa,format('select to_jsonb(public.platform_set_tenant_plan_v1(%L,%L))',t,'booking_only_v1'))->>'state'='00000');
 perform pg_temp.assert_true('unknown target blocked',not(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'unknown'))->'value'->>'can_apply')::boolean);
 perform pg_temp.assert_true('upgrade full',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,%L,%L,%L)',t,'current_full_v1','1',gen_random_uuid()))->>'state'='00000');
 perform pg_temp.assert_true('public remains private',not(select is_public from public.tenant_public_profiles where tenant_id=t));
 perform pg_temp.assert_true('safe downgrade', (pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);

 perform set_config('app.product10d_test_enforce','off',true);
 update public.tenants set status='active' where id=t;
 insert into public.tenant_memberships(tenant_id,user_id,role,status)values(t,other_user,'admin','active');
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value';
 perform pg_temp.assert_true('full current plan',p->'current_plan'->>'plan_key'='current_full_v1');
 perform pg_temp.assert_true('full removal nine features',jsonb_array_length(p->'features_removed')=9 and jsonb_array_length(p->'features_added')=0);
 perform pg_temp.assert_true('capability-only reports calendar branding warnings',(select count(*)=3 from jsonb_array_elements(p->'warnings') x where x->>'code'='CAPABILITY_REMOVED'));
 insert into public.events(id,tenant_id,title,event_date,start_time,end_time,location,price,max_participants,is_active)values(e,t,'PII-SENTINEL event',current_date-10,'10:00','11:00','Local',0,10,false);
 perform pg_temp.assert_true('closed historical event allowed',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 update public.events set event_date=current_date+10,is_active=true where id=e;
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value';
 perform pg_temp.assert_true('future event blocks',p->'blockers' @> '[{"code":"EVENTS_OPEN","count":1}]');
 perform pg_temp.assert_true('unsafe event downgrade via current UI v1 denied',pg_temp.rpc(pa,format('select to_jsonb(public.platform_set_tenant_plan_v1(%L,%L))',t,'booking_only_v1'))->>'state'='55000');
 perform pg_temp.assert_true('preview no event details',p::text not like '%PII-SENTINEL%');
 update public.events set is_active=false where id=e;
 insert into public.event_registrations(id,tenant_id,event_id,user_id,customer_name,customer_email,customer_phone,registration_status,payment_status)values(reg,t,e,other_user,'PII-SENTINEL customer','pii-sentinel@example.invalid','555-PII','registered','free');
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value';
 perform pg_temp.assert_true('open registration blocks inactive future event',p->'blockers' @> '[{"code":"EVENT_REGISTRATIONS_OPEN","count":1}]');
 perform pg_temp.assert_true('preview no customer PII',p::text not like '%PII-SENTINEL%' and p::text not like '%pii-sentinel%' and p::text not like '%555-PII%');
 update public.event_registrations set registration_status='reserve' where id=reg;
 perform pg_temp.assert_true('reserve blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"EVENT_REGISTRATIONS_OPEN"}]');
 update public.event_registrations set registration_status='cancelled' where id=reg;
 update public.events set event_date=current_date-10 where id=e;
 perform pg_temp.assert_true('cancelled historical registration excluded',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 update public.event_registrations set registration_status='registered' where id=reg;
 perform pg_temp.assert_true('past unmarked attendance blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"EVENT_REGISTRATIONS_OPEN"}]');
 update public.event_registrations set registration_status='cancelled' where id=reg;
 insert into public.event_instructors(tenant_id,event_id,instructor_user_id,assigned_by)values(t,e,other_user,other_user);
 raise notice 'HISTORICAL_WITH_PENDING_NOTICE=%',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1')); update public.email_deliveries set delivery_state='failed',attempt_count=3,last_error_code='retry_exhausted',attempt_window_started_at=now()-interval '24 hours',last_attempt_at=now() where tenant_id=t; perform pg_temp.assert_true('retry-exhausted history mail is not claimable',public.claim_instructor_email_batch_v1(e)='[]'::jsonb); perform pg_temp.assert_true('terminal retry-exhausted historical notices should not block', (pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean); perform pg_temp.assert_true('historical instructor assignment with resolved notices excluded',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 update public.events set event_date=current_date+10 where id=e;
 perform pg_temp.assert_true('future instructor assignment blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"INSTRUCTORS_ACTIVE"}]');
 update public.events set event_date=current_date-10 where id=e;
 perform pg_temp.pam_keeper(t);
 update public.tenant_memberships set role='employee' where tenant_id=t and user_id=other_user;
 perform pg_temp.assert_true('active employee blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"STAFF_ACTIVE"}]');
 update public.tenant_memberships set status='suspended' where tenant_id=t and user_id=other_user;
 perform pg_temp.assert_true('suspended employee excluded',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 update public.tenant_memberships set role='admin',status='active' where tenant_id=t and user_id=other_user;
 insert into public.shooting_lanes(id,tenant_id,name,type,is_active,max_shooters,booking_step_minutes,display_order,currency_code,resource_kind,whole_lane_bookable,positions_bookable)values(lane,t,'PAM lane','test',true,2,60,901,'PLN','lane',true,false);
 insert into public.lane_blocks(tenant_id,lane_id,block_date,start_time,end_time,reason,is_active)values(t,lane,current_date-10,'10:00','11:00','Historical',true);
 perform pg_temp.assert_true('expired lane block excluded',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 update public.lane_blocks set block_date=current_date+10 where tenant_id=t;
 perform pg_temp.assert_true('future lane block blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"LANE_BLOCKS_ACTIVE"}]');
 update public.lane_blocks set block_date=current_date-10 where tenant_id=t;
 insert into public.lane_pricing_rules(id,lane_id,day_group,min_shooters,max_shooters,label,hourly_price,display_order,is_active)values(price_id,lane,'mon_thu',1,2,'PAM',10,1,true);
 insert into public.reservations(id,user_id,tenant_id,lane_id,customer_name,customer_email,customer_phone,reservation_date,start_time,end_time,duration_minutes,price,reservation_status,payment_status,attendance_status,shooters_count,pricing_rule_id,pricing_day_group_snapshot,lane_name_snapshot,pricing_label_snapshot,price_per_hour_snapshot,total_price,currency_code,creation_request_id)values(reservation_id,other_user,t,lane,'PII-SENTINEL','pii-sentinel@example.invalid','555-PII',current_date-10,'10:00','11:00',60,10,'confirmed','pay_on_site','planned',1,price_id,'mon_thu','PAM','PAM',10,10,'PLN',gen_random_uuid());
 perform pg_temp.assert_true('past unresolved reservation blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"CHECKIN_OBLIGATION"}]');
 update public.reservations set reservation_status='completed',attendance_status='completed',checked_in_at=now(),completed_at=now() where id=reservation_id;
 perform pg_temp.assert_true('completed reservation excluded',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 perform set_config('app.product10d_test_enforce','on',true);
 r:=pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''add'',null,''pam-probe.test'')',t));d:=(r->'value'->>'id')::uuid;
 perform pg_temp.assert_true('custom-domain add with entitlement',r->>'state'='00000');
 perform pg_temp.assert_true('pending domain permits downgrade',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 challenge:=pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''start_verification'',%L)',t,d))->'value';
 perform public.operator_verify_tenant_domain_v1(d,1,challenge->>'txt_value','csk-booking-5nwh',true);
 perform pg_temp.assert_true('verified inactive domain permits downgrade',(pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->>'can_apply')::boolean);
 perform pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''activate'',%L)',t,d));
 perform pg_temp.assert_true('active custom domain blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"CUSTOM_DOMAIN_ACTIVE"}]');
 perform pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''set_primary'',%L)',t,d));
 perform pg_temp.assert_true('primary custom domain blocks',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'booking_only_v1'))->'value'->'blockers' @> '[{"code":"CUSTOM_DOMAIN_ACTIVE"}]');
 perform pg_temp.assert_true('v1 cannot bypass custom-domain blocker',pg_temp.rpc(pa,format('select to_jsonb(public.platform_set_tenant_plan_v1(%L,%L))',t,'booking_only_v1'))->>'state'='55000');
 perform pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''disable'',%L)',t,d));
 before_flags:=(select to_jsonb(public_profile) from public.tenant_public_profiles public_profile where tenant_id=t);
 r:=pg_temp.rpc(pa,format('select to_jsonb(public.platform_set_tenant_plan_v1(%L,%L))',t,'booking_only_v1'));
 perform pg_temp.assert_true('current UI v1 safe allowed downgrade succeeds',r->>'state'='00000');
 perform pg_temp.assert_true('v1 change single audit and revision',(select revision=3 from public.tenant_plan_assignments where tenant_id=t) and (select count(*)=3 from public.platform_audit_logs where tenant_id=t and action in ('plan_assigned','plan_changed')));
 perform pg_temp.assert_true('downgrade preserves public profile',before_flags=(select to_jsonb(public_profile) from public.tenant_public_profiles public_profile where tenant_id=t));
 perform pg_temp.assert_true('terminal email history retained after actual v1 downgrade',exists(select 1 from public.email_deliveries where tenant_id=t and last_error_code='retry_exhausted' and attempt_count=3));
 perform pg_temp.assert_true('history retained',exists(select 1 from public.events where id=e) and exists(select 1 from public.event_registrations where id=reg) and exists(select 1 from public.reservations where id=reservation_id));
 perform pg_temp.assert_true('My Events history after downgrade',pg_temp.rpc(other_user,format('select public.get_my_event_registrations_v2(%L,''history'',null,1,20)',t))->>'state'='00000');
 perform pg_temp.assert_true('My Reservations after downgrade',pg_temp.rpc(other_user,format('select public.get_my_reservations_v3(%L,1,50)',t))->>'state'='00000');
 perform pg_temp.assert_true('account export after downgrade',pg_temp.rpc(other_user,'select public.export_my_data_v3()')->>'state'='00000');
 perform pg_temp.assert_true('continuity after downgrade',(pg_temp.rpc(other_user,'select public.get_my_continuity_v1(1,null)')->'value'->>'total')::int=2);
 perform pg_temp.assert_true('no-entitlement custom-domain add denied',pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''add'',null,''pam-denied.test'')',t))->>'state'='42501');
 perform set_config('app.product10d_test_enforce','off',true);
 update public.tenant_domains set status='verified',verified_at=now(),verification_expires_at=now()+interval '1 day' where id=d;
 perform set_config('app.product10d_test_enforce','on',true);
 perform pg_temp.assert_true('no-entitlement activate denied',pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''activate'',%L)',t,d))->>'state'='42501');
 perform set_config('app.product10d_test_enforce','off',true);
 update public.tenant_domains set status='active',is_primary=true where id=d;
 update public.tenant_public_profiles set is_public=true,show_events=true where tenant_id=t;
 perform set_config('app.product10d_test_enforce','on',true);
 perform pg_temp.assert_true('no-entitlement set primary denied',pg_temp.rpc(pa,format('select public.platform_manage_tenant_domain_v1(%L,''set_primary'',%L)',t,d))->>'state'='42501');
 perform pg_temp.assert_true('resolver hides unsupported custom domain',pg_temp.rpc(null,'select public.resolve_public_tenant_domain_v1(''pam-probe.test'')')->'value'='null'::jsonb);
 perform pg_temp.assert_true('primary-domain reader hides unsupported custom domain',pg_temp.rpc(null,'select to_jsonb(public.get_public_tenant_primary_domain_v1(''pam-local-public''))')->'value'='null'::jsonb);
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'current_full_v1'))->'value';
 perform pg_temp.assert_true('retained show_events public upgrade blocked',p->'blockers' @> '[{"code":"PUBLIC_REEXPOSURE","feature_key":"events"}]');
 perform pg_temp.assert_true('retained custom-domain upgrade blocked',p->'blockers' @> '[{"code":"DOMAIN_REEXPOSURE"}]');
 perform pg_temp.assert_true('upgrade cannot bypass preview',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,%L,%L,%L)',t,'current_full_v1','3',gen_random_uuid()))->>'state'='55000');
 perform pg_temp.assert_true('v1 cannot bypass upgrade exposure blocker',pg_temp.rpc(pa,format('select to_jsonb(public.platform_set_tenant_plan_v1(%L,%L))',t,'current_full_v1'))->>'state'='55000');
 perform set_config('app.product10d_test_enforce','off',true);
 update public.tenant_domains set status='disabled',is_primary=false where id=d;
 update public.tenant_public_profiles set is_public=false where tenant_id=t;
 perform set_config('app.product10d_test_enforce','on',true);
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,%L)',t,'current_full_v1'))->'value';
 perform pg_temp.assert_true('private retained flags warn, allow upgrade',(p->>'can_apply')::boolean and p->'warnings' @> '[{"code":"RETAINED_PUBLIC_FLAGS"}]');
 perform pg_temp.rpc(pa,format('select to_jsonb(public.platform_set_tenant_state_v1(%L,''suspend''))',t));
 perform pg_temp.assert_true('suspended owner continuity retained',(pg_temp.rpc(other_user,'select public.get_my_continuity_v1(1,null)')->'value'->>'total')::int=2);
 perform pg_temp.assert_true('suspended export allowed',pg_temp.rpc(other_user,'select public.export_my_data_v3()')->>'state'='00000');
 perform pg_temp.assert_true('same plan no-op',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,%L,%L,%L)',t,'booking_only_v1','3',gen_random_uuid()))->'value'->>'code'='no_change');

 -- General My pages deliberately exclude suspended tenants; continuity is the supported suspended reader.
 perform pg_temp.assert_true('suspended My Events existing not_found contract',pg_temp.rpc(other_user,format('select public.get_my_event_registrations_v2(%L,''history'',null,1,20)',t))->'value'->>'code'='not_found');
 perform pg_temp.assert_true('suspended settlement after downgrade',pg_temp.rpc(other_user,format('select to_jsonb(public.record_external_settlement_v1(''external_reconciliation'',''reservation'',%L,10,''PLN'',''PAM diagnostic'',%L))',reservation_id,gen_random_uuid()))->>'state'='00000');
 perform pg_temp.assert_true('cancelled event continuation after downgrade',pg_temp.rpc(other_user,format('select public.cancel_continuity_resource_v1(''event_registration'',%L)',reg))->'value'->>'changed'='false');
 perform pg_temp.assert_true('unknown target writer denied',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,''unknown'',''3'',%L)',t,gen_random_uuid()))->>'state'='22023');
 perform pg_temp.assert_true('malformed target writer denied',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,''BAD!'',''3'',%L)',t,gen_random_uuid()))->>'state'='22023');
 insert into public.saas_plans(plan_key,status)values('pam_inactive_v1','inactive');
 perform pg_temp.assert_true('inactive target preview blocker',pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,''pam_inactive_v1'')',t))->'value'->'blockers' @> '[{"code":"TARGET_PLAN_INACTIVE"}]');
 perform pg_temp.assert_true('inactive target writer denied',pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,''pam_inactive_v1'',''3'',%L)',t,gen_random_uuid()))->>'state'='22023');
 perform set_config('app.product10d_test_enforce','off',true);
 update public.tenants set status='active' where id=t;
 update public.tenant_public_profiles set is_public=true,show_events=false where tenant_id=t;
 perform set_config('app.product10d_test_enforce','on',true);
 perform pg_temp.assert_true('My Events history preserved active after downgrade',(pg_temp.rpc(other_user,format('select public.get_my_event_registrations_v2(%L,''history'',null,1,20)',t))->'value'->'pagination'->>'total')::int=1);
 perform pg_temp.assert_true('My Reservations count after downgrade',(pg_temp.rpc(other_user,format('select public.get_my_reservations_v3(%L,1,50)',t))->'value'->'pagination'->>'total')::int=1);
 perform pg_temp.assert_true('platform slug still resolves',pg_temp.rpc(null,'select to_jsonb(public.resolve_active_tenant_by_slug_v1(''pam-local''))')->'value'->>'tenant_id'=t::text);
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,''current_full_v1'')',t))->'value';
 perform pg_temp.assert_true('no-show retained flags allows public upgrade',(p->>'can_apply')::boolean);
 r:=pg_temp.rpc(pa,format('select public.platform_change_tenant_plan_v2(%L,''current_full_v1'',''3'',%L)',t,gen_random_uuid()));
 perform pg_temp.assert_true('upgrade after explicit visibility review allowed',r->>'state'='00000');
 r:=pg_temp.rpc(other_user,format('select public.admin_create_event_v3(%L,''Cancellation probe'',null,current_date+12,''10:00'',''11:00'',''Local'',0,10,''{}'')',t));
 e:=(r->'value'->>'event_id')::uuid;
 perform pg_temp.assert_true('cancellation fixture real event RPC',r->'value'->>'ok'='true');
 perform set_config('app.product10d_test_enforce','off',true);
 insert into public.event_registrations(tenant_id,event_id,user_id,customer_name,customer_email,customer_phone,registration_status,payment_status)values(t,e,other_user,'Local cancel','cancel@example.invalid','000','registered','free');
 perform set_config('app.product10d_test_enforce','on',true);
 r:=pg_temp.rpc(other_user,format('select public.admin_cancel_event_v1(%L)',e));
 perform pg_temp.assert_true('event cancellation real RPC',r->>'state'='00000' and r->'value'->>'code'='cancelled');
 p:=pg_temp.rpc(pa,format('select public.platform_get_tenant_plan_change_preview_v1(%L,''booking_only_v1'')',t))->'value';
 perform pg_temp.assert_true('cancelled event pending notification blocks',p->'blockers' @> '[{"code":"EVENT_EMAIL_OBLIGATIONS"}]');
 perform pg_temp.assert_true('cancelled event no future active-event blocker',not(p->'blockers' @> '[{"code":"EVENTS_OPEN"}]'));
 perform set_config('app.product10d_test_enforce','off',true);
 update public.tenant_memberships set role='employee' where tenant_id=t and user_id=other_user;
 perform pg_temp.assert_true('employee cannot preview',pg_temp.rpc(other_user,format('select public.platform_get_tenant_plan_change_preview_v1(%L,''booking_only_v1'')',t))->>'state'='42501');
 perform pg_temp.assert_true('employee cannot write',pg_temp.rpc(other_user,format('select public.platform_change_tenant_plan_v2(%L,''current_full_v1'',''4'',%L)',t,gen_random_uuid()))->>'state'='42501');
 update public.tenant_memberships set role='instructor' where tenant_id=t and user_id=other_user;
 perform pg_temp.assert_true('instructor cannot write',pg_temp.rpc(other_user,format('select public.platform_change_tenant_plan_v2(%L,''current_full_v1'',''4'',%L)',t,gen_random_uuid()))->>'state'='42501');
 update public.tenant_memberships set role='user' where tenant_id=t and user_id=other_user;
 perform pg_temp.assert_true('user cannot write',pg_temp.rpc(other_user,format('select public.platform_change_tenant_plan_v2(%L,''current_full_v1'',''4'',%L)',t,gen_random_uuid()))->>'state'='42501');

 update public.platform_admins set status='suspended' where user_id=pa;
 perform pg_temp.assert_true('suspended PA denied',pg_temp.rpc(pa,q)->>'state'='42501'); delete from public.platform_admins where user_id=pa; perform pg_temp.assert_true('removed PA denied',pg_temp.rpc(pa,q)->>'state'='42501');
end;$test$;

do $matrix$
declare d public.email_deliveries; kind text;
begin
 foreach kind in array array['event_reserve_acceptance_confirmation','event_registration_cancellation','event_cancellation','instructor_assignment','instructor_removal','instructor_event_cancellation','event_reminder_24h'] loop
  d:=jsonb_populate_record(null::public.email_deliveries,jsonb_build_object('message_type',kind,'delivery_state','pending','attempt_count',0));
  perform pg_temp.assert_true(kind||' pending blocks',public.plan_change_email_is_open_v1(d));
  d.delivery_state:='sending';d.attempt_count:=3;d.claim_id:=gen_random_uuid();d.claim_expires_at:=statement_timestamp()+interval '5 minutes';
  perform pg_temp.assert_true(kind||' active final lease blocks',public.plan_change_email_is_open_v1(d));
  d.claim_id:=null;d.claim_expires_at:=null;d.delivery_state:='failed';d.attempt_count:=1;d.attempt_window_started_at:=statement_timestamp();d.last_error_code:='delivery_failed_or_uncertain';
  perform pg_temp.assert_true(kind||' retryable failure blocks',public.plan_change_email_is_open_v1(d));
  d.attempt_count:=3;d.last_error_code:='retry_exhausted';
  perform pg_temp.assert_true(kind||' exhausted failure excluded',not public.plan_change_email_is_open_v1(d));
  d.attempt_count:=1;d.attempt_window_started_at:=statement_timestamp()-interval '24 hours';
  perform pg_temp.assert_true(kind||' expired window matches actual claim contract',public.plan_change_email_is_open_v1(d)=(kind='event_reminder_24h'));
  d.delivery_state:='sent';d.sent_at:=statement_timestamp();
  perform pg_temp.assert_true(kind||' sent excluded',not public.plan_change_email_is_open_v1(d));
 end loop;
 d:=jsonb_populate_record(null::public.email_deliveries,'{"message_type":"event_reminder_24h","delivery_state":"failed","attempt_count":1,"last_error_code":"ineligible"}');
 perform pg_temp.assert_true('ineligible reminder terminal excluded',not public.plan_change_email_is_open_v1(d));
 d:=jsonb_populate_record(null::public.email_deliveries,'{"message_type":"event_registration_confirmation","attempt_count":3}');
 perform pg_temp.assert_true('legacy daily confirmation cap is not terminal',public.plan_change_email_is_open_v1(d));
 d.sent_at:=statement_timestamp();
 perform pg_temp.assert_true('legacy sent confirmation excluded',not public.plan_change_email_is_open_v1(d));
 perform pg_temp.assert_true('closed lifecycle helper no client execute',not has_function_privilege('authenticated','public.plan_change_email_is_open_v1(public.email_deliveries)','EXECUTE') and not has_function_privilege('anon','public.plan_change_email_is_open_v1(public.email_deliveries)','EXECUTE') and not has_function_privilege('service_role','public.plan_change_email_is_open_v1(public.email_deliveries)','EXECUTE'));
end;$matrix$;

select '1..'||count(*) from results;
select (case when passed then 'ok ' else 'not ok ' end)||n||' - '||label from results order by n;
rollback;
select 'FIXTURE_CLEANUP='||count(*) from public.tenants where slug='pam-local';