import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createClient} from '@supabase/supabase-js';
import {test,expect} from '@playwright/test';
import {getLocalSupabaseTestEnvironment} from './local-supabase';
const env=getLocalSupabaseTestEnvironment(),db=process.env.ONBOARD_1C_DATABASE;
if(!/^onboard_1c_[0-9a-f]{16}$/.test(db??''))throw Error('ISOLATED_SCRATCH_DATABASE_REQUIRED');
const service=createClient(env.supabaseUrl,env.serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});
const sql=(s:string)=>execFileSync('docker',['exec','supabase_db_csk-booking','psql','-X','-At','-v','ON_ERROR_STOP=1','-U','postgres','-d',db!,'-c',s],{encoding:'utf8'}).trim();
const localClient=()=>createClient(env.supabaseUrl,env.anonKey,{auth:{persistSession:false,autoRefreshToken:false}});
test('dormant setup: validation, persistence, conflicts, legacy, responsive and isolation',async({page})=>{
 const run=randomUUID(),tenant=randomUUID(),tenantA=randomUUID(),slug=`validation-${run}`,password=`Local-${run}!Aa9`;
 const users:string[]=[];const actors:Record<string,ReturnType<typeof localClient>>={};
 try{
  for(const role of ['admin','other-admin','user','employee','instructor','pa']){
   const email=`${role}-${run}@example.invalid`,created=await service.auth.admin.createUser({email,password,email_confirm:true});
   if(created.error||!created.data.user)throw Error('LOCAL_AUTH_FIXTURE');const user=created.data.user.id;users.push(user);
   const client=localClient();const signed=await client.auth.signInWithPassword({email,password});expect(signed.error).toBeNull();actors[role]=client;
  }
  sql(`insert into public.tenants(id,name,slug,status)values('${tenant}','Synthetic','${slug}','dormant');insert into public.tenant_plan_assignments(tenant_id,plan_id,status)select '${tenant}',id,'active'from public.saas_plans where plan_key='current_full_v1';insert into public.tenant_public_profiles(tenant_id,display_name,city,is_public,public_slug,show_booking,show_pricing,show_instructor,show_events,show_about,show_contact,show_regulations)values('${tenant}','Synthetic','Testowo',false,'pub-${slug}',false,false,false,false,false,false,false);insert into public.tenant_memberships(tenant_id,user_id,role,status)values('${tenant}','${users[0]}','admin','active'),('${tenant}','${users[3]}','employee','active'),('${tenant}','${users[4]}','instructor','active');insert into public.platform_admins(user_id,status)values('${users[5]}','active');`);
  sql(`insert into public.tenants(id,name,slug,status)values('${tenantA}','Synthetic A','a-${slug}','dormant');insert into public.tenant_plan_assignments(tenant_id,plan_id,status)select '${tenantA}',id,'active'from public.saas_plans where plan_key='current_full_v1';insert into public.tenant_memberships(tenant_id,user_id,role,status)values('${tenantA}','${users[1]}','admin','active');insert into public.tenant_public_profiles(tenant_id,display_name,city,is_public,public_slug)values('${tenantA}','Synthetic A','Testowo',false,'pub-a-${slug}');`);
  const ownA=await actors['other-admin'].rpc('admin_get_tenant_public_settings_v1',{p_tenant_slug:`a-${slug}`});expect(ownA.error).toBeNull();const {feature_access:featuresA,updated_at:stampA,...payloadA}=ownA.data;expect(featuresA.booking).toBe(true);expect((await actors['other-admin'].rpc('admin_update_tenant_public_settings_v1',{p_tenant_slug:`a-${slug}`,p_settings:payloadA,p_expected_updated_at:stampA})).error).toBeNull();
  await page.goto('/login?redirectTo=%2Fdashboard');await page.getByLabel('E-mail',{exact:true}).fill(`admin-${run}@example.invalid`);await page.getByLabel('Hasło',{exact:true}).fill(password);await page.getByRole('button',{name:'Zaloguj się',exact:true}).click();await expect(page).toHaveURL(/\/dashboard$/);
  page.on('requestfailed',r=>{if(r.url().includes('/rpc/'))console.log('LOCAL_RPC_REQUEST_FAILED',r.failure()?.errorText);});page.on('response',r=>{if(r.url().endsWith('/rpc/admin_update_tenant_public_settings_v1'))console.log('LOCAL_SETTINGS_STATUS',r.status());});
  await page.goto(`/tenant-setup/${slug}`);const field=(key:string)=>page.locator(`[data-field="${key}"]`);const save=()=>page.getByRole('button',{name:'Zapisz i zostań',exact:true}).click();
  await expect(field('display_name')).toHaveValue('Synthetic');await save();await expect(page.getByText('Ustawienia zapisane.')).toBeVisible();await page.reload();await expect(field('city')).toHaveValue('Testowo');
  let calls=0;page.on('request',r=>{if(r.url().endsWith('/rpc/admin_update_tenant_public_settings_v1'))calls++;});
  for(const [key,value]of [['public_email','bad'],['logo_path','logo'],['hero_image_path','https://example.invalid'],['regulations_path','/a/../b'],['facebook','https://'],['instagram','https://'],['youtube','https://']]as const){
   const before=calls;await field(key).fill(value);await save();await expect(field(key)).toHaveAttribute('aria-invalid','true');await expect(field(key)).toBeFocused();await expect(page.locator('div[role=alert]').filter({hasNot:page.locator('#__next-route-announcer__')}).filter({hasText:/Popraw zaznaczone|Ustawienia zostały/})).toContainText('Popraw zaznaczone pola.');expect(calls).toBe(before);await expect(field(key)).toHaveValue(value);await field(key).fill('');
  }
  await field('openingTime').fill('07:00');await save();await expect(field('closingTime')).toHaveAttribute('aria-invalid','true');await field('openingTime').fill('');await field('closingTime').fill('22:00');await save();await expect(field('openingTime')).toHaveAttribute('aria-invalid','true');
  await field('openingTime').fill('22:00');await save();await expect(page.getByText('Godzina zamknięcia musi być późniejsza niż godzina otwarcia.')).toBeVisible();await field('closingTime').fill('21:00');await save();await expect(field('closingTime')).toHaveAttribute('aria-invalid','true');
  await field('public_email').fill(' public@example.invalid ');await field('openingTime').fill('07:00');await field('closingTime').fill('22:00');await field('logo_path').fill('/brand/logo.png');await save();await expect(page.getByText('Ustawienia zapisane.')).toBeVisible();await page.reload();await expect(field('public_email')).toHaveValue('public@example.invalid');await expect(field('openingTime')).toHaveValue('07:00');await expect(field('closingTime')).toHaveValue('22:00');
  const dto=await actors.admin.rpc('admin_get_tenant_public_settings_v1',{p_tenant_slug:slug});expect(dto.error).toBeNull();const {feature_access:features,updated_at:stamp,...payload}=dto.data;expect(features.booking).toBe(true);
  for(const role of ['other-admin','user','employee','instructor','pa']){
   const read=await actors[role].rpc('admin_get_tenant_public_settings_v1',{p_tenant_slug:slug});expect(read.error?.code).toBe('42501');const denied=await actors[role].rpc('admin_update_tenant_public_settings_v1',{p_tenant_slug:slug,p_settings:payload,p_expected_updated_at:stamp});expect(denied.error?.code).toBe('42501');
  }
  const invalid=await actors.admin.rpc('admin_update_tenant_public_settings_v1',{p_tenant_slug:slug,p_settings:{...payload,public_email:'bad'},p_expected_updated_at:stamp});expect(invalid.error?.code).toBe('23514');
  sql(`update public.tenant_public_profiles set opening_hours='Pon.–Pt. 8–20'where tenant_id='${tenant}';`);await page.reload();await expect(page.getByText('Pon.–Pt. 8–20',{exact:true})).toBeVisible();await save();await expect(page.getByText('Ustawienia zapisane.')).toBeVisible();expect(sql(`select opening_hours from public.tenant_public_profiles where tenant_id='${tenant}'`)).toBe('Pon.–Pt. 8–20');await page.getByRole('button',{name:'Zastąp dotychczasowy zapis godzin'}).click();await field('openingTime').fill('07:00');await field('closingTime').fill('22:00');
  for(const width of [320,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);const a=await field('openingTime').boundingBox(),b=await field('closingTime').boundingBox();expect(a).not.toBeNull();expect(b).not.toBeNull();if(width===320)expect(b!.y).toBeGreaterThan(a!.y);if(width===1440)expect(b!.y).toBe(a!.y);}
  // Simulate the precise known response, retaining inputs and giving focus to email.
  await page.route('**/rpc/admin_update_tenant_public_settings_v1',r=>r.request().method()==='OPTIONS'?r.continue():r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({code:'23514',message:'new row violates check constraint "tenant_public_profiles_public_email_check"'})}));await save();await expect(page.getByText('Podaj poprawny adres e-mail albo pozostaw pole puste.')).toBeVisible();await expect(field('public_email')).toBeFocused();await expect(field('logo_path')).toHaveValue('/brand/logo.png');await page.unroute('**/rpc/admin_update_tenant_public_settings_v1');
  expect(sql(`select status||':'||is_public from public.tenants t join public.tenant_public_profiles p on p.tenant_id=t.id where t.id='${tenant}'`)).toBe('dormant:false');
  console.log('LOCAL_INDEPENDENT_MATRIX_PASS; CROSS_TENANT_AND_ROLE_NEGATIVES_PASS; LEGACY_AND_RESPONSIVE_PASS');
  await page.reload();await expect(field('display_name')).toHaveValue('Synthetic');
  const latest=await actors.admin.rpc('admin_get_tenant_public_settings_v1',{p_tenant_slug:slug});expect(latest.error).toBeNull();const {feature_access:latestFeatures,updated_at:latestStamp,...latestPayload}=latest.data;expect(latestFeatures.booking).toBe(true);expect(latestStamp).toBeTruthy();
  const concurrent=await actors.admin.rpc('admin_update_tenant_public_settings_v1',{p_tenant_slug:slug,p_settings:{...latestPayload,city:'Concurrent'},p_expected_updated_at:latest.data.updated_at});expect(concurrent.error).toBeNull();await field('city').fill('My unsaved city');await save();await expect(page.locator('div[role=alert]').filter({hasNot:page.locator('#__next-route-announcer__')}).filter({hasText:/Popraw zaznaczone|Ustawienia zostały/})).toContainText('Ustawienia zostały zmienione w innym miejscu.',{timeout:60000});await expect(field('city')).toHaveValue('My unsaved city');await page.getByRole('button',{name:'Odśwież dane (zastąpi wpisane wartości)'}).click();await expect(field('city')).toHaveValue('Concurrent');
 }finally{
  for(const id of [tenant,tenantA])sql(`delete from public.audit_logs where tenant_id='${id}';delete from public.tenant_memberships where tenant_id='${id}';delete from public.tenant_public_profiles where tenant_id='${id}';delete from public.tenant_plan_assignments where tenant_id='${id}';delete from public.tenants where id='${id}';`);
  for(const user of users){sql(`delete from public.platform_admins where user_id='${user}';`);const removed=await service.auth.admin.deleteUser(user);expect(removed.error).toBeNull();}
  expect(sql('select count(*) from auth.users')).toBe('0');
 }
});
