-- Add an admin-only atomic creator for complete lane families.
-- Resource UUIDs are generated by PostgreSQL; display names are not technical identity.

do $preflight$
declare
  v_table_name text;
begin
if not exists (
  select 1
  from supabase_migrations.schema_migrations
  where version in (
    '20260815221500',
    '20260816090000'
  )
) then
  raise exception 'Lane family creation preflight failed: required migration or baseline is missing.';
end if;

  foreach v_table_name in array array[
    'shooting_lanes',
    'lane_booking_rules',
    'lane_booking_durations',
    'lane_pricing_rules',
    'lane_booking_family_configuration_versions',
    'profiles',
    'audit_logs'
  ]::text[]
  loop
    if pg_catalog.to_regclass('public.' || v_table_name) is null then
      raise exception 'Lane family creation preflight failed: public.% is missing.',
        v_table_name;
    end if;
  end loop;

  if pg_catalog.to_regprocedure(
       'public.admin_create_lane_booking_family_v1(jsonb)'
     ) is not null
     or exists (
       select 1
       from pg_catalog.pg_proc as procedure
       join pg_catalog.pg_namespace as namespace
         on namespace.oid = procedure.pronamespace
       where namespace.nspname = 'public'
         and procedure.proname = 'admin_create_lane_booking_family_v1'
     ) then
    raise exception 'Lane family creation preflight failed: creator already exists.';
  end if;

  if pg_catalog.to_regprocedure(
       'public.admin_get_lane_booking_configuration_v2()'
     ) is null
     or pg_catalog.to_regprocedure(
       'public.admin_set_lane_booking_family_configuration_v2(uuid,bigint,jsonb,boolean)'
     ) is null then
    raise exception 'Lane family creation preflight failed: V2 read/write contract is missing.';
  end if;

  foreach v_table_name in array array[
    'shooting_lanes',
    'lane_booking_rules',
    'lane_booking_durations',
    'lane_pricing_rules'
  ]::text[]
  loop
    if not exists (
         select 1
         from pg_catalog.pg_class as table_record
         where table_record.oid = ('public.' || v_table_name)::pg_catalog.regclass
           and table_record.relrowsecurity
           and not table_record.relforcerowsecurity
       )
       or pg_catalog.has_table_privilege(
         'authenticated', 'public.' || v_table_name, 'INSERT'
       )
       or pg_catalog.has_table_privilege(
         'authenticated', 'public.' || v_table_name, 'UPDATE'
       )
       or pg_catalog.has_table_privilege(
         'authenticated', 'public.' || v_table_name, 'DELETE'
       )
       or pg_catalog.has_table_privilege('anon', 'public.' || v_table_name, 'INSERT')
       or pg_catalog.has_table_privilege('anon', 'public.' || v_table_name, 'UPDATE')
       or pg_catalog.has_table_privilege('anon', 'public.' || v_table_name, 'DELETE')
       or exists (
         select 1
         from pg_catalog.pg_class as table_record
         cross join lateral pg_catalog.aclexplode(
           coalesce(
             table_record.relacl,
             pg_catalog.acldefault('r', table_record.relowner)
           )
         ) as acl
         where table_record.oid = ('public.' || v_table_name)::pg_catalog.regclass
           and acl.grantee = 0
           and acl.privilege_type in ('INSERT', 'UPDATE', 'DELETE')
       ) then
      raise exception 'Lane family creation preflight failed: public.% write hardening differs.',
        v_table_name;
    end if;
  end loop;
end;
$preflight$;

create function public.admin_create_lane_booking_family_v1(p_family jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path to pg_catalog, public, pg_temp
as $function$
declare
  v_actor_id uuid := auth.uid();
  v_actor public.profiles%rowtype;
  v_actor_role text;
  v_root jsonb;
  v_positions jsonb;
  v_resources jsonb;
  v_resource record;
  v_price record;
  v_root_id uuid;
  v_position_id uuid;
  v_root_display_order integer;
  v_created_resources jsonb := '[]'::jsonb;
  v_created_count integer := 0;
  v_position_capacity integer := 0;
  v_now timestamptz := pg_catalog.transaction_timestamp();
begin
  select profile.*
  into v_actor
  from public.profiles as profile
  where profile.user_id = v_actor_id;

  v_actor_role := pg_catalog.lower(pg_catalog.btrim(v_actor.role::text));
  if v_actor_id is null or coalesce(v_actor_role, '') <> 'admin' then
    return pg_catalog.jsonb_build_object(
      'ok', false,
      'changed', false,
      'code', 'not_allowed',
      'root_lane_id', null,
      'configuration_version', null,
      'created_resource_count', 0
    );
  end if;

  begin
    if p_family is null
       or pg_catalog.jsonb_typeof(p_family) <> 'object'
       or (
         select pg_catalog.array_agg(key order by key)
         from pg_catalog.jsonb_object_keys(p_family) as keys(key)
       ) is distinct from array['positions', 'root']::text[]
       or pg_catalog.jsonb_typeof(p_family->'root') <> 'object'
       or pg_catalog.jsonb_typeof(p_family->'positions') <> 'array'
       or pg_catalog.jsonb_array_length(p_family->'positions') > 100 then
      return pg_catalog.jsonb_build_object(
        'ok', false, 'changed', false, 'code', 'invalid_payload',
        'root_lane_id', null, 'configuration_version', null,
        'created_resource_count', 0
      );
    end if;

    v_root := p_family->'root';
    v_positions := p_family->'positions';

    if (
         select pg_catalog.array_agg(key order by key)
         from pg_catalog.jsonb_object_keys(v_root) as keys(key)
       ) is distinct from array[
         'booking_step_minutes', 'durations_minutes', 'is_active',
         'max_people_online', 'max_shooters', 'name', 'online_bookable',
         'positions_bookable', 'pricing', 'whole_lane_bookable'
       ]::text[]
       or exists (
         select 1
         from pg_catalog.jsonb_array_elements(v_positions) as position(value)
         where pg_catalog.jsonb_typeof(position.value) <> 'object'
            or (
              select pg_catalog.array_agg(key order by key)
              from pg_catalog.jsonb_object_keys(position.value) as keys(key)
            ) is distinct from array[
              'booking_step_minutes', 'durations_minutes', 'is_active',
              'max_people_online', 'max_shooters', 'name', 'online_bookable',
              'pricing'
            ]::text[]
       ) then
      return pg_catalog.jsonb_build_object(
        'ok', false, 'changed', false, 'code', 'invalid_payload',
        'root_lane_id', null, 'configuration_version', null,
        'created_resource_count', 0
      );
    end if;

    select pg_catalog.jsonb_build_array(
      v_root || pg_catalog.jsonb_build_object(
        'resource_kind', 'lane'
      )
    ) || coalesce(pg_catalog.jsonb_agg(
      position.value || pg_catalog.jsonb_build_object(
        'resource_kind', 'position',
        'whole_lane_bookable', false,
        'positions_bookable', false
      ) order by position.ordinality
    ), '[]'::jsonb)
    into v_resources
    from pg_catalog.jsonb_array_elements(v_positions) with ordinality
      as position(value, ordinality);

    for v_resource in
      select resource.value, resource.ordinality
      from pg_catalog.jsonb_array_elements(v_resources) with ordinality
        as resource(value, ordinality)
      order by resource.ordinality
    loop
      if pg_catalog.jsonb_typeof(v_resource.value->'name') <> 'string'
         or pg_catalog.btrim(v_resource.value->>'name') = ''
         or pg_catalog.char_length(pg_catalog.btrim(v_resource.value->>'name')) > 120
         or v_resource.value->>'name' ~ '[<>]'
         or v_resource.value->>'name' ~ '[[:cntrl:]]'
         or pg_catalog.jsonb_typeof(v_resource.value->'is_active') <> 'boolean'
         or pg_catalog.jsonb_typeof(v_resource.value->'online_bookable') <> 'boolean'
         or pg_catalog.jsonb_typeof(v_resource.value->'whole_lane_bookable') <> 'boolean'
         or pg_catalog.jsonb_typeof(v_resource.value->'positions_bookable') <> 'boolean'
         or pg_catalog.jsonb_typeof(v_resource.value->'max_shooters') <> 'number'
         or v_resource.value->>'max_shooters' !~ '^[1-9][0-9]*$'
         or pg_catalog.jsonb_typeof(v_resource.value->'max_people_online') <> 'number'
         or v_resource.value->>'max_people_online' !~ '^[1-9][0-9]*$'
         or pg_catalog.jsonb_typeof(v_resource.value->'booking_step_minutes') <> 'number'
         or v_resource.value->>'booking_step_minutes' !~ '^[1-9][0-9]*$'
         or (v_resource.value->>'booking_step_minutes')::integer > 1440
         or (v_resource.value->>'max_people_online')::integer
              > (v_resource.value->>'max_shooters')::integer
         or pg_catalog.jsonb_typeof(v_resource.value->'durations_minutes') <> 'array'
         or pg_catalog.jsonb_array_length(v_resource.value->'durations_minutes') = 0
         or pg_catalog.jsonb_typeof(v_resource.value->'pricing') <> 'array'
         or pg_catalog.jsonb_array_length(v_resource.value->'pricing') = 0 then
        return pg_catalog.jsonb_build_object(
          'ok', false, 'changed', false, 'code', 'invalid_payload',
          'root_lane_id', null, 'configuration_version', null,
          'created_resource_count', 0
        );
      end if;

      if exists (
           select 1
           from pg_catalog.jsonb_array_elements(
             v_resource.value->'durations_minutes'
           ) as duration(value)
           where pg_catalog.jsonb_typeof(duration.value) <> 'number'
              or duration.value #>> '{}' !~ '^[1-9][0-9]*$'
              or (duration.value #>> '{}')::integer > 1440
              or (duration.value #>> '{}')::integer
                   % (v_resource.value->>'booking_step_minutes')::integer <> 0
         )
         or (
           select pg_catalog.count(*)
           from pg_catalog.jsonb_array_elements(
             v_resource.value->'durations_minutes'
           )
         ) <> (
           select pg_catalog.count(distinct duration.value #>> '{}')
           from pg_catalog.jsonb_array_elements(
             v_resource.value->'durations_minutes'
           ) as duration(value)
         ) then
        return pg_catalog.jsonb_build_object(
          'ok', false, 'changed', false, 'code', 'invalid_configuration',
          'root_lane_id', null, 'configuration_version', null,
          'created_resource_count', 0
        );
      end if;

      for v_price in
        select price.value
        from pg_catalog.jsonb_array_elements(v_resource.value->'pricing')
          as price(value)
      loop
        if pg_catalog.jsonb_typeof(v_price.value) <> 'object'
           or (
             select pg_catalog.array_agg(key order by key)
             from pg_catalog.jsonb_object_keys(v_price.value) as keys(key)
           ) is distinct from array[
             'day_group', 'hourly_price', 'label', 'max_shooters', 'min_shooters'
           ]::text[]
           or pg_catalog.jsonb_typeof(v_price.value->'day_group') <> 'string'
           or v_price.value->>'day_group' not in ('mon_thu', 'fri_sun')
           or pg_catalog.jsonb_typeof(v_price.value->'label') <> 'string'
           or pg_catalog.btrim(v_price.value->>'label') = ''
           or pg_catalog.jsonb_typeof(v_price.value->'min_shooters') <> 'number'
           or v_price.value->>'min_shooters' !~ '^[1-9][0-9]*$'
           or pg_catalog.jsonb_typeof(v_price.value->'max_shooters') <> 'number'
           or v_price.value->>'max_shooters' !~ '^[1-9][0-9]*$'
           or pg_catalog.jsonb_typeof(v_price.value->'hourly_price') <> 'number'
           or v_price.value->>'hourly_price' !~ '^[0-9]+([.][0-9]{1,2})?$'
           or (v_price.value->>'min_shooters')::integer
                > (v_price.value->>'max_shooters')::integer
           or (v_price.value->>'max_shooters')::integer
                > (v_resource.value->>'max_people_online')::integer
           or (v_price.value->>'hourly_price')::numeric > 9999999999.99 then
          return pg_catalog.jsonb_build_object(
            'ok', false, 'changed', false, 'code', 'invalid_payload',
            'root_lane_id', null, 'configuration_version', null,
            'created_resource_count', 0
          );
        end if;
      end loop;

      if exists (
           with parsed as (
             select
               price.value->>'day_group' as day_group,
               (price.value->>'min_shooters')::integer as min_shooters,
               (price.value->>'max_shooters')::integer as max_shooters,
               pg_catalog.lag((price.value->>'max_shooters')::integer) over (
                 partition by price.value->>'day_group'
                 order by (price.value->>'min_shooters')::integer,
                          (price.value->>'max_shooters')::integer
               ) as previous_max
             from pg_catalog.jsonb_array_elements(v_resource.value->'pricing')
               as price(value)
           )
           select 1 from parsed
           where (previous_max is null and min_shooters <> 1)
              or (previous_max is not null and min_shooters <> previous_max + 1)
         )
         or (
           select pg_catalog.count(*)
           from (
             select price.value->>'day_group' as day_group
             from pg_catalog.jsonb_array_elements(v_resource.value->'pricing')
               as price(value)
             group by price.value->>'day_group'
             having pg_catalog.max((price.value->>'max_shooters')::integer)
                    = (v_resource.value->>'max_people_online')::integer
           ) as complete_group
         ) <> 2 then
        return pg_catalog.jsonb_build_object(
          'ok', false, 'changed', false, 'code', 'invalid_configuration',
          'root_lane_id', null, 'configuration_version', null,
          'created_resource_count', 0
        );
      end if;
    end loop;
  exception
    when sqlstate '22003' or sqlstate '22P02' then
      return pg_catalog.jsonb_build_object(
        'ok', false, 'changed', false, 'code', 'invalid_payload',
        'root_lane_id', null, 'configuration_version', null,
        'created_resource_count', 0
      );
  end;

  if (v_root->>'online_bookable')::boolean
       and (not (v_root->>'is_active')::boolean
            or not (v_root->>'whole_lane_bookable')::boolean)
     or not (v_root->>'is_active')::boolean
       and (
         (v_root->>'online_bookable')::boolean
         or exists (
           select 1
           from pg_catalog.jsonb_array_elements(v_positions) as position(value)
           where (position.value->>'is_active')::boolean
              or (position.value->>'online_bookable')::boolean
         )
       )
     or exists (
       select 1
       from pg_catalog.jsonb_array_elements(v_positions) as position(value)
       where (position.value->>'online_bookable')::boolean
         and (
           not (position.value->>'is_active')::boolean
           or not (v_root->>'positions_bookable')::boolean
         )
     )
     or (
       (v_root->>'positions_bookable')::boolean
       and not exists (
         select 1
         from pg_catalog.jsonb_array_elements(v_positions) as position(value)
         where (position.value->>'is_active')::boolean
           and (position.value->>'online_bookable')::boolean
       )
     ) then
    return pg_catalog.jsonb_build_object(
      'ok', false, 'changed', false, 'code', 'invalid_configuration',
      'root_lane_id', null, 'configuration_version', null,
      'created_resource_count', 0
    );
  end if;

  select coalesce(pg_catalog.sum((position.value->>'max_shooters')::integer), 0)
  into v_position_capacity
  from pg_catalog.jsonb_array_elements(v_positions) as position(value)
  where (position.value->>'is_active')::boolean
    and (position.value->>'online_bookable')::boolean;

  if (v_root->>'positions_bookable')::boolean
     and v_position_capacity > (v_root->>'max_shooters')::integer then
    return pg_catalog.jsonb_build_object(
      'ok', false, 'changed', false, 'code', 'invalid_configuration',
      'root_lane_id', null, 'configuration_version', null,
      'created_resource_count', 0
    );
  end if;

  lock table public.shooting_lanes in share row exclusive mode;

  select coalesce(pg_catalog.max(lane.display_order), 0) + 10
  into v_root_display_order
  from public.shooting_lanes as lane;

  v_root_id := pg_catalog.gen_random_uuid();
  insert into public.shooting_lanes(
    id, name, type, description, price_per_hour, is_active,
    max_shooters, booking_step_minutes, display_order, currency_code,
    resource_kind, parent_lane_id, whole_lane_bookable, positions_bookable
  ) values (
    v_root_id,
    pg_catalog.btrim(v_root->>'name'),
    'konfigurowalna',
    null,
    0,
    (v_root->>'is_active')::boolean,
    (v_root->>'max_shooters')::integer,
    (v_root->>'booking_step_minutes')::integer,
    v_root_display_order,
    'PLN',
    'lane',
    null,
    (v_root->>'whole_lane_bookable')::boolean,
    (v_root->>'positions_bookable')::boolean
  );

  insert into public.lane_booking_rules(lane_id, online_bookable, max_people_online)
  values (
    v_root_id,
    (v_root->>'online_bookable')::boolean,
    (v_root->>'max_people_online')::integer
  );

  insert into public.lane_booking_durations(
    lane_id, duration_minutes, display_order, is_active
  )
  select
    v_root_id,
    (duration.value #>> '{}')::integer,
    duration.ordinality * 10,
    true
  from pg_catalog.jsonb_array_elements(v_root->'durations_minutes') with ordinality
    as duration(value, ordinality);

  insert into public.lane_pricing_rules(
    lane_id, day_group, min_shooters, max_shooters,
    label, hourly_price, display_order, is_active
  )
  select
    v_root_id,
    price.value->>'day_group',
    (price.value->>'min_shooters')::integer,
    (price.value->>'max_shooters')::integer,
    pg_catalog.btrim(price.value->>'label'),
    (price.value->>'hourly_price')::numeric(12,2),
    pg_catalog.row_number() over (
      partition by price.value->>'day_group'
      order by (price.value->>'min_shooters')::integer,
               (price.value->>'max_shooters')::integer,
               pg_catalog.btrim(price.value->>'label')
    ) * 10,
    true
  from pg_catalog.jsonb_array_elements(v_root->'pricing') as price(value);

  v_created_resources := pg_catalog.jsonb_build_array(
    pg_catalog.jsonb_build_object(
      'resource_id', v_root_id,
      'resource_kind', 'lane',
      'name', pg_catalog.btrim(v_root->>'name')
    )
  );
  v_created_count := 1;

  for v_resource in
    select position.value, position.ordinality
    from pg_catalog.jsonb_array_elements(v_positions) with ordinality
      as position(value, ordinality)
    order by position.ordinality
  loop
    v_position_id := pg_catalog.gen_random_uuid();
    insert into public.shooting_lanes(
      id, name, type, description, price_per_hour, is_active,
      max_shooters, booking_step_minutes, display_order, currency_code,
      resource_kind, parent_lane_id, whole_lane_bookable, positions_bookable
    ) values (
      v_position_id,
      pg_catalog.btrim(v_resource.value->>'name'),
      'konfigurowalna',
      null,
      0,
      (v_resource.value->>'is_active')::boolean,
      (v_resource.value->>'max_shooters')::integer,
      (v_resource.value->>'booking_step_minutes')::integer,
      v_root_display_order + v_resource.ordinality::integer,
      'PLN',
      'position',
      v_root_id,
      false,
      false
    );

    insert into public.lane_booking_rules(lane_id, online_bookable, max_people_online)
    values (
      v_position_id,
      (v_resource.value->>'online_bookable')::boolean,
      (v_resource.value->>'max_people_online')::integer
    );

    insert into public.lane_booking_durations(
      lane_id, duration_minutes, display_order, is_active
    )
    select
      v_position_id,
      (duration.value #>> '{}')::integer,
      duration.ordinality * 10,
      true
    from pg_catalog.jsonb_array_elements(
      v_resource.value->'durations_minutes'
    ) with ordinality as duration(value, ordinality);

    insert into public.lane_pricing_rules(
      lane_id, day_group, min_shooters, max_shooters,
      label, hourly_price, display_order, is_active
    )
    select
      v_position_id,
      price.value->>'day_group',
      (price.value->>'min_shooters')::integer,
      (price.value->>'max_shooters')::integer,
      pg_catalog.btrim(price.value->>'label'),
      (price.value->>'hourly_price')::numeric(12,2),
      pg_catalog.row_number() over (
        partition by price.value->>'day_group'
        order by (price.value->>'min_shooters')::integer,
                 (price.value->>'max_shooters')::integer,
                 pg_catalog.btrim(price.value->>'label')
      ) * 10,
      true
    from pg_catalog.jsonb_array_elements(v_resource.value->'pricing')
      as price(value);

    v_created_resources := v_created_resources || pg_catalog.jsonb_build_array(
      pg_catalog.jsonb_build_object(
        'resource_id', v_position_id,
        'resource_kind', 'position',
        'name', pg_catalog.btrim(v_resource.value->>'name')
      )
    );
    v_created_count := v_created_count + 1;
  end loop;

  insert into public.lane_booking_family_configuration_versions(
    root_lane_id, configuration_version
  ) values (v_root_id, 1);

  insert into public.audit_logs(
    actor_user_id, actor_name, actor_role, action,
    target_type, target_id, target_name, details
  ) values (
    v_actor_id,
    coalesce(
      nullif(
        pg_catalog.btrim(
          pg_catalog.concat_ws(' ', v_actor.first_name, v_actor.last_name)
        ),
        ''
      ),
      nullif(pg_catalog.btrim(v_actor.full_name), ''),
      'Administrator'
    ),
    'admin',
    'lane_booking_family_created',
    'lane_booking_family',
    v_root_id,
    pg_catalog.btrim(v_root->>'name'),
    pg_catalog.jsonb_build_object(
      'configuration_version', 1,
      'created_resources', v_created_resources,
      'created_at', v_now
    )
  );

  return pg_catalog.jsonb_build_object(
    'ok', true,
    'changed', true,
    'code', 'created',
    'root_lane_id', v_root_id,
    'configuration_version', 1,
    'created_resource_count', v_created_count
  );
end;
$function$;

alter function public.admin_create_lane_booking_family_v1(jsonb) owner to postgres;

comment on function public.admin_create_lane_booking_family_v1(jsonb) is
  'Atomically creates one complete lane family with server-generated resource UUIDs.';

revoke all on function public.admin_create_lane_booking_family_v1(jsonb) from public;
revoke all on function public.admin_create_lane_booking_family_v1(jsonb) from anon;
revoke all on function public.admin_create_lane_booking_family_v1(jsonb) from authenticated;
revoke all on function public.admin_create_lane_booking_family_v1(jsonb) from service_role;
grant execute on function public.admin_create_lane_booking_family_v1(jsonb) to authenticated;

do $postflight$
declare
  v_creator pg_catalog.regprocedure :=
    'public.admin_create_lane_booking_family_v1(jsonb)'::pg_catalog.regprocedure;
  v_procedure pg_catalog.pg_proc%rowtype;
begin
  if (
       select pg_catalog.count(*)
       from pg_catalog.pg_proc as procedure
       join pg_catalog.pg_namespace as namespace
         on namespace.oid = procedure.pronamespace
       where namespace.nspname = 'public'
         and procedure.proname = 'admin_create_lane_booking_family_v1'
     ) <> 1 then
    raise exception 'Lane family creation postflight failed: unexpected overload count.';
  end if;

  select procedure.*
  into strict v_procedure
  from pg_catalog.pg_proc as procedure
  where procedure.oid = v_creator;

  if not v_procedure.prosecdef
     or v_procedure.provolatile <> 'v'
     or v_procedure.proowner <> (
       select role.oid from pg_catalog.pg_roles as role where role.rolname = 'postgres'
     )
     or v_procedure.prorettype <> 'pg_catalog.jsonb'::pg_catalog.regtype
     or v_procedure.proconfig is distinct from
        array['search_path=pg_catalog, public, pg_temp']::text[]
     or not pg_catalog.has_function_privilege('authenticated', v_creator, 'EXECUTE')
     or pg_catalog.has_function_privilege('anon', v_creator, 'EXECUTE')
     or pg_catalog.has_function_privilege('service_role', v_creator, 'EXECUTE')
     or exists (
       select 1
       from pg_catalog.aclexplode(
         coalesce(
           v_procedure.proacl,
           pg_catalog.acldefault('f', v_procedure.proowner)
         )
       ) as acl
       where acl.grantee = 0
         and acl.privilege_type = 'EXECUTE'
     ) then
    raise exception 'Lane family creation postflight failed: security contract differs.';
  end if;
end;
$postflight$;
